name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  version_of_release: # id of input
    description: 'texttt'
    required: true
    default: 'The most important changes are downgrading the artifact to java7 (from 8) and switching to gmavenplus plugin to compile groovy.
          Besides that, there is a lot of restructuring inside of the pom.xml file

          # Misc

          * Polishing (f2ec0bb, 9e2ae89 and 8654493)

          _Reviewed by_: @neslob'  
  
outputs:
  ver: # id of output
    description: 'vvv'
runs:
  using: 'node12'
  main: 'dist/index.js'
