on:
  push:
    paths:
      - release.yml
    branches:
      - file_change_trigger
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    # steps:
    # - name: Tag commit
    #   uses: tvdias/github-tagger@v0.0.1
    #   with:
    #     repo-token: "${{ secrets.GITHUB_TOKEN }}"
    #     tag: "my_tag"
    
    name: release notes
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
      - run: 
            echo ${{ steps.hello.outputs}}
            description=${{ steps.hello.outputs.ver }}
            echo $description
            description="${description//'%'/'%25'}" 
            description="${description//$'\n'/'%0A'}"
            description="${description//$'\r'/'%0D'}" 
            echo $description
            echo "::set-output name=test::$description"
  
  # release_note:
  #       name: Create Release
  #       runs-on: ubuntu-latest
  #       needs: hello_world_job
  #       steps:
  #         - name: Checkout code
  #           uses: actions/checkout@v2
  #            # Use the output from the `hello` step
  #         - name: Get the output time
  #           run: echo "This vhhhhers  ${{needs.hello_world_job.outputs.output1}}"
  #         - name: Create Release
  #           id: create_release
  #           uses: actions/create-release@v1
  #           env:
  #             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
  #           with:
  #             tag_name: ${{ github.ref }}
  #             release_name: Release ${{ github.ref }}
  #             body: |
  #               ${{needs.hello_world_job.outputs.output1}}
  #             draft: false
  #             prerelease: false  