on:
  push:
    paths:
      - release.yml
    branches:
      - file_change_trigger
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    # steps:
    # - name: Tag commit
    #   uses: tvdias/github-tagger@v0.0.1
    #   with:
    #     repo-token: "${{ secrets.GITHUB_TOKEN }}"
    #     tag: "my_tag"
    
    name: release notes
    outputs:
      latest_release_tag: ${{ steps.step1.outputs.tag }}
      latest_release_body: ${{ steps.step1.outputs.body }}
      test: ${{ steps.step1.outputs.testing }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run:  npm install
              npm run build
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
      - run: 
            #echo ${{ steps.hello.outputs}}
            description=${{ steps.hello.outputs.lat_body }}
            echo "::set-output name=testing::$description"
            description="${description//'%'/'%25'}" 
            description="${description//$'\n'/'%0A'}"
            description="${description//$'\r'/'%0D'}" 
            echo $description
            echo "::set-output name=body::$description"
            echo "::set-output name=tag::${{ steps.hello.outputs.lat_tag }}"
  
  release_note:
        name: Create Release
        runs-on: ubuntu-latest
        needs: hello_world_job
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
             # Use the output from the `hello` step
          - name: Get the output time
            run: echo "This vhhhhers  ${{needs.hello_world_job.outputs.test}}"
          - name: Create Release
            id: create_release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
            with:
              tag_name: ${{needs.hello_world_job.outputs.latest_release_tag}}
              release_name: Release ${{needs.hello_world_job.outputs.latest_release_tag}}
              body: |
                ${{needs.hello_world_job.outputs.latest_release_body}}
              draft: false
              prerelease: false  